version: '3.9'

services:
  autorizador:
    image: autorizador
    container_name: autorizador
    build:
      context: ./
    dns:
      - 8.8.8.8
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_SERVER_URL=http://keycloak:8080
      - KEYCLOAK_REALM=medisupply-realm
      - KEYCLOAK_CLIENT_ID=medisupply-app
    networks:
      - medisupply-net

networks:
  medisupply-net:
    external: true